package uk.gov.ons.census.fwmt.outcomeservice.enums;

public enum EventType {

  FULFILMENT_REQUESTED,
  QUESTIONNAIRE_LINKED,
  REFUSAL_RECEIVED,
  ADDRESS_NOT_VALID,
  ADDRESS_TYPE_CHANGED,

  CONTACT_NOT_NEEDED,
  POTENTIAL_RESIDENTIAL,

  CCS_ADDRESS_LISTED

}
