package uk.gov.ons.census.fwmt.outcomeservice.enums;

public enum EventType {

  // Household
  FULFILMENT_REQUESTED,
  QUESTIONNAIRE_LINKED,
  REFUSAL_RECEIVED,
  ADDRESS_NOT_VALID,
  ADDRESS_TYPE_CHANGED,

  // CCS
  CONTACT_NOT_NEEDED,
  POTENTIAL_RESIDENTIAL,
  COLLECT_CE_DETAILS,
  CCS_CE_OUT_OF_SCOPE,
  NON_RESIDENTIAL

}
